name: majimo_timer
description: A new Flutter project.

publish_to: "none"

version: 0.6.9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_links: ^3.2.0
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.6.17
  cupertino_back_gesture: ^0.1.0
  dart_date: ^1.1.0
  dismissible_page: ^0.7.3
  duration_picker: ^1.1.0+1
  easy_localization: ^3.0.0
  flag: ^6.0.0
  flutter:
    sdk: flutter
  flutter_color: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_custom_tabs: ^1.0.4
  flutter_grid_button: ^2.0.0
  flutter_hooks: ^0.18.0
  flutter_styled_toast: ^2.0.0
  flutter_windowmanager: ^0.2.0
  flutter_expanded_tile: ^0.3.6
  freezed_annotation: ^2.0.3
  fullscreen: ^1.0.3
  hooks_riverpod: ^1.0.0
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  percent_indicator: ^4.0.0
  quick_actions: ^0.6.0+8
  reorderables: ^0.5.0
  ripple_backdrop_animate_route: ^1.0.0
  rive: ^0.9.0
  rxdart: ^0.27.4
  simple_animations: ^4.0.1
  slide_digital_clock: ^1.0.2
  tap_to_expand: ^0.5.7
  wakelock: ^0.6.1+2

dev_dependencies:
  build_runner: ^2.1.7
  dependency_validator: ^3.2.0
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  pedantic_mono: ^1.15.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/splash/splash.png
  color: "#ff6600"
  color_dark: "#ff5521"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/splash/
    - assets/l10n/

  fonts:
    - family: M-plus-B
      fonts:
        - asset: assets/fonts/MPLUS1p-Bold.ttf
          style: normal
          weight: 500

    - family: M-plus-M
      fonts:
        - asset: assets/fonts/MPLUS1p-Medium.ttf
          style: normal
          weight: 400
